package tj.dfns.utils;

public interface Credentials {
    // C3P0 SERVICE TOKEN - When creating the service accounts - copy/paste this
    public static String DEFAULT_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSJ9.eyJpc3MiOiJhdXRoLmRmbnMubmluamEiLCJhdWQiOiJkZm5zOmF1dGg6dXNlciIsInN1YiI6Im9yLTFpYWE1LTlybjNmLTlpdXF2ODRzanBmaGNqaGUiLCJqdGkiOiJ0by02ZWVwMy0wZ3Nxdi05YWFidGYzYzdvaGlpbzZwIiwic2NvcGUiOiIiLCJwZXJtaXNzaW9ucyI6W10sImh0dHBzOi8vY3VzdG9tL3VzZXJuYW1lIjoiMzdjIiwiaHR0cHM6Ly9jdXN0b20vYXBwX21ldGFkYXRhIjp7InVzZXJJZCI6InVzLTZrNDRxLWFvaWd2LTk5MDg0ZWszaDBkcmM1aWEiLCJvcmdJZCI6Im9yLTFpYWE1LTlybjNmLTlpdXF2ODRzanBmaGNqaGUiLCJ0b2tlbktpbmQiOiJTZXJ2aWNlQWNjb3VudCJ9LCJpYXQiOjE3MjYwNDg2ODYsImV4cCI6MTc4OTEyMDY4Nn0.Im0JwBf8pjtfBwmQU6KhJrwMNbVBddpWlQL1azLMujs9fGC9hUOmEG0Zx_X6AWaoCNAxhJqDdNYGWC6YI4KlBA";
}
